---
name: ci

on:
  push:
    branches:
      - main
      - develop
      - 'releases/**'
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+-pre'
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
      - develop

jobs:
  preflight-job:
    name: Preflight Step
    runs-on: ubuntu-latest
    steps:
      - run: env
