---
name: Test

on:
  workflow_run:
    workflows:
      - ci
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+-pre'
    types:
      - completed

jobs:
  test-job:
    name: Test Step
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
      - run: git branch
      - run: env
